spring:
    profiles:
        active: dev
    config:
        import:
            - application-db.yml
            - application-oauth.yml

    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
